### ISSUE TITLE
Issue with the scanning second sheet "sheet-2"

### ISSUE THREAD

**Issue by NileshM3** [m-cakir/bubble-sheet-multiple-choice-scanner#2]
I'm not able to scan "sheet-2" you have provided in the Library links.
& also not able to scan images of the same samples you have provided in the library.

Please help me as soon as possible with the same.

Thank you in advance!

**Comment by Mohanedy98** [comment]
The Same Issue Here

**Comment by m-cakir** [comment]
What is the error? Please, give more detail.

**Comment by Mohanedy98** [comment]
The Error is that the program scans only the samples you provided but can't scan any other image like this one for example
[https://imgur.com/a/BMOauFl](url)

**Comment by m-cakir** [comment]
its not ready for production usage yet, just an example. Still has unstable situations like threshold values for luminosity or optimal bubble sizes etc.
